version: 2.1
workflows:
  testing:
    jobs:
      - runner1
      - runner2
      - runner3
      - runner4
      - runner5
      - runner6
  scaling:
    jobs:
      - scale
jobs:
  scale:
    machine: true
    resource_class: danielholdsworth/macos-resource-class
    steps:
      - checkout
      - run: ./scale.sh
  runner1:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 1!"
  runner2:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 2!"
  runner3:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 3!"
  runner4:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 4!!"
  runner5:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 5!"
  runner6:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 6!"
