version: 2.1
orbs:
  docker: circleci/docker@2.0.1

jobs:       
  build: 
      docker:
        - image: cimg/base
      steps: 
        - checkout
        - setup_remote_docker:
            version: 19.03.13
        - run: 
            name: Build Docker Image
            command: |
              docker build -t testimage/test .

workflows:
  docker-build:
    jobs:
      - build
