version: 2.1
workflows:
  testing:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm on Docker Runner!"
