version: 2.1
workflows:
  testing:
    jobs:
      - runner-1
      - runner-2
jobs:
  runner-1:
    machine: true
    resource_class: danielholdsworth/ubuntu-resource-class
    steps:
      - run: echo "Hi I'm on Runner 1!"
  runner-2:
    machine: true
    resource_class: danielholdsworth/ubuntu2-resource-class
    steps:
      - run: echo "Hi I'm on Runner 2!"
