version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0.0

workflows:
  #testing:
    #jobs:
      #- runner1
      #- runner2
      #- runner3
      #- runner4
      #- runner5
      #- runner6
  #scaling:
    #jobs:
      #- scale
  linux:
    jobs:
      - linux-server
  s3_pull_job:
    jobs:
      - s3-pull

jobs:
  s3-pull:
    docker:
    # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - aws-s3/copy:
          to: . 
          from: s3://ip-range-test-again/cat.jpg
  linux-server:
    circleci_ip_ranges: true
    machine: true
    resource_class: danielholdsworth/ubuntu-resource-class
    steps:
      - run: echo "Hi I'm Running on an Ubuntu Server!"
  scale:
    machine: true
    resource_class: danielholdsworth/macos-resource-class
    steps:
      - checkout
      - run: ./scale.sh
  runner1:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 1!"
  runner2:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 2!"
  runner3:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 3!"
  runner4:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 4!!"
  runner5:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 5!"
  runner6:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 6!"
