version: 2.1
workflows:
  testing:
    jobs:
      - runner1
      - runner2
      - runner3
jobs:
  runner1:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 1!" ; pwd
  runner2:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 2!" ; pwd
  runner3:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 3!" ; pwd
