version: 2.1

workflows:
  #testing:
    #jobs:
      #- runner1
      #- runner2
      #- runner3
      #- runner4
      #- runner5
      #- runner6
  #scaling:
    #jobs:
      #- scale
  linux:
    jobs:
      - linux-server
  ip_range_test:
    jobs:
      - ip-test

jobs:
  ip-test:
    circleci_ip_ranges: true
    docker:
      - image: cimg/base:stable
    steps:
      - run: sudo apt update; sudo apt install iputils-ping 
      - run: ping -c 4 18.188.90.159
  linux-server:
    circleci_ip_ranges: true
    machine: true
    resource_class: danielholdsworth/ubuntu-resource-class
    steps:
      - run: echo "Hi I'm Running on an Ubuntu Server!"
  scale:
    machine: true
    resource_class: danielholdsworth/macos-resource-class
    steps:
      - checkout
      - run: ./scale.sh
  runner1:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 1!"
  runner2:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 2!"
  runner3:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 3!"
  runner4:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 4!!"
  runner5:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 5!"
  runner6:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 6!"
