version: 2.1

auth: &ghcrconfig
  username: $GHCR_USERNAME
  password: $GHCR_PASSWORD

workflows:
  testing:
    jobs:
      - runner1
      - runner2
      - runner3
      - runner4
      - runner5
      - runner6
  scaling:
    jobs:
      - scale
  ghcr:
    jobs:
      - ghcr-test
      
  linux-rerun-test:
    jobs:
      - linux-rerun

jobs:
  linux-rerun:
    machine: true
    resource_class: danielholdsworth/ubuntu-resource-class
    steps:
      - run: echo "test"
  ghcr-test:
    docker:
      - image: ghcr.io/danielholdsworth/runner-test:amd64
        auth: *ghcrconfig 
    steps:
      - checkout
  scale:
    machine: true
    resource_class: danielholdsworth/macos-resource-class
    steps:
      - checkout
      - run: ./scale.sh
  runner1:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 1!"
  runner2:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 2!"
  runner3:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 3!"
  runner4:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 4!!"
  runner5:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 5!"
  runner6:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 6!"
