version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.1.0

workflows:
  #testing:
    #jobs:
      #- runner1
      #- runner2
      #- runner3
      #- runner4
      #- runner5
      #- runner6
  #scaling:
    #jobs:
      #- scale
  linux:
    jobs:
      - linux-server
  cli_install:
    jobs:
      - install-cli
jobs:
  install-cli:
    docker:
      - image: cimg/base:stable
    steps:
      - aws-cli/install
      - run: mkdir ~/.aws; touch ~/.aws/credentials
      - run: aws s3 cp s3://dan-ip-range/cat.jpg cat.jpg
  linux-server: 
    circleci_ip_ranges: true
    machine: true
    resource_class: danielholdsworth/ubuntu-resource-class
    steps:
      - run: echo "Hi I'm Running on an Ubuntu Server!"
  scale:
    machine: true
    resource_class: danielholdsworth/macos-resource-class
    steps:
      - checkout
      - run: ./scale.sh
  runner1:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 1!"
  runner2:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 2!"
  runner3:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 3!"
  runner4:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 4!!"
  runner5:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 5!"
  runner6:
    machine: true
    resource_class: danielholdsworth/docker-resource-class
    steps:
      - run: echo "Hi I'm runner job 6!"
